name: ExecuTorch Demo Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Enable uv caching
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.4"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest tests
          
